# Generated by Django 5.1.6 on 2025-02-10 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=200)),
                ('head_of_department', models.CharField(choices=[('JA', 'Dr. John Anderson'), ('EC', 'Dr. Emily Carter'), ('MT', 'Dr. Michael Thompson'), ('SM', 'Dr. Sarah Mitchell'), ('DW', 'Dr. David Wilson')], max_length=2)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('c', 'Closed')], default='a', max_length=1)),
                ('descriptions', models.TextField()),
                ('location', models.TextField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon raqami faqat raqamlardan iborat bo‘lishi va 7-15 ta belgidan oshmasligi kerak.', regex='^\\+?\\d{7,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
